In [1]:
import numpy as np

In [2]:
a, b = np.load("train.npz"), np.load("test.npz")

In [3]:
a.keys(), b.keys()

(['mask_train', 'partition', 'X_train', 'y_train'],
 ['X_test', 'mask_test', 'y_test'])

In [4]:
# to divide the set in 4 folds for better training
print(len(a['partition']))
len(a['y_train'][np.where(a['partition']==4)])

4763


1188

In [5]:
# each seq is a 1000x20 matrix
len(a['X_train'][0]), len(a['X_train']), a['X_train'][0][0:3]

(1000,
 4763,
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0.]], dtype=float32))

In [6]:
# don't really know what's for this mask, it just has 1s and 0s to correspond some protein regions
# MASK DATASET ONLY USEFUL FOR LSTM PATCH -- GOODBYE
print(len(a['mask_train']),
len(a['mask_train'][0]),
     a['mask_train'][0][0:160],
     a['mask_train'][12])


4763 1000 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

In [7]:
# Y variables for training
print(len(a['y_train']),
     a['y_train'][1:100])

4763 [6 6 6 6 6 6 6 2 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 6 6 6 6 6 6 6 6 1 1 1 1 1
 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 9 9 9 9 2 4 9 9 4 4 5 4 4 6 6 6 6 6 6 6 6 2
 2 4 4 2 2 2 2 2 2 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0]


In [8]:
len(b['y_test'])

1195

In [9]:
for seq in a['X_train'][:150]:
    print(seq.shape)

(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)
(1000, 20)

In [10]:
for i in a['X_train'][234]:
    print(i)

[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.18 0.44 0.   0.35 0.
 0.   0.   0.   0.   0.   0.03]
[0.06 0.21 0.   0.   0.   0.03 0.01 0.   0.03 0.02 0.04 0.23 0.01 0.02
 0.02 0.18 0.03 0.   0.09 0.01]
[0.02 0.01 0.   0.   0.02 0.   0.01 0.02 0.01 0.12 0.26 0.   0.04 0.31
 0.   0.01 0.06 0.   0.04 0.07]
[0.07 0.01 0.   0.   0.02 0.   0.   0.01 0.01 0.1  0.36 0.   0.   0.17
 0.01 0.06 0.02 0.   0.01 0.15]
[0.04 0.   0.   0.   0.06 0.01 0.   0.01 0.   0.24 0.23 0.   0.01 0.08
 0.02 0.01 0.06 0.   0.01 0.21]
[0.07 0.   0.   0.   0.02 0.   0.   0.01 0.   0.15 0.36 0.   0.   0.14
 0.   0.02 0.02 0.   0.01 0.19]
[0.09 0.01 0.   0.   0.03 0.   0.   0.02 0.   0.08 0.32 0.   0.02 0.18
 0.01 0.08 0.02 0.   0.01 0.14]
[0.28 0.   0.01 0.   0.07 0.01 0.   0.05 0.   0.06 0.21 0.   0.01 0.03
 0.01 0.14 0.04 0.   0.   0.09]
[0.12 0.   0.   0.   0.04 0.   0.   0.02 0.   0.11 0.37 0.   0.01 0.14
 0.   0.03 0.04 0.   0.01 0.12]
[0.12 0.   0.01 0.   0.06 0.   0.   0.   0.   0.13 0.19 0.   0.01 0.07
 0.0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0

In [15]:
cnt = 0
for i in a['X_train']:
    for v in i:
        if sum(v) == 0:
            cnt += 1
    print(cnt)
    cnt = 0
            
print(cnt)

840
874
857
833
870
887
869
871
683
838
137
115
129
489
455
464
559
900
899
683
901
876
688
833
683
212
612
636
776
499
499
801
424
835
462
462
0
739
706
848
848
503
897
787
792
463
453
831
521
686
684
217
135
801
609
601
614
652
485
591
663
281
44
408
663
278
798
783
784
788
780
799
431
784
830
590
97
231
913
0
793
802
831
903
772
199
243
224
230
707
565
563
439
215
343
345
717
106
698
144
100
94
290
540
485
493
516
521
454
461
486
534
537
526
764
764
587
846
846
857
850
841
845
839
619
257
373
262
0
264
0
0
624
748
234
0
213
380
468
0
0
331
370
53
51
528
605
599
595
612
522
364
712
816
284
249
920
918
600
883
899
827
827
888
880
884
886
665
547
639
526
252
521
628
492
0
13
0
759
544
544
344
329
217
0
561
808
851
303
273
850
788
792
311
400
210
180
828
239
94
271
207
224
240
694
750
691
756
747
805
807
766
915
943
938
446
772
156
543
545
692
777
596
765
581
856
826
852
626
423
553
477
643
854
859
397
648
489
936
859
828
782
779
652
810
783
576
783
968
627
622
0
426
641
645
480
817
819

135
598
587
804
702
678
697
66
542
502
550
494
490
498
900
895
265
325
527
656
212
765
794
555
510
694
712
424
472
543
506
433
502
268
220
533
543
533
394
501
504
526
524
622
856
850
852
861
853
852
848
684
360
287
471
754
601
564
297
1
714
926
742
82
188
480
773
588
499
795
870
605
413
452
404
393
394
407
853
903
365
0
696
825
846
667
312
749
373
326
625
658
690
715
659
704
596
743
739
750
655
810
811
811
811
814
821
831
417
624
641
620
625
630
594
587
597
0
91
0
140
146
127
611
628
447
869
579
816
146
97
864
858
859
718
247
563
119
310
987
415
874
585
598
599
208
611
813
895
704
594
480
583
240
299
625
480
625
626
644
751
0
467
36
30
642
33
301
829
866
958
0
493
480
0
50
182
203
205
205
176
186
268
209
194
820
746
362
935
836
904
879
875
826
823
817
543
189
719
802
813
379
0
703
0
616
237
371
0
508
508
508
508
495
508
508
681
804
583
769
833
538
594
598
846
847
839
844
558
784
502
504
705
705
706
715
715
714
252
790
584
583
636
348
0
633
883
0
430
263
746
254
315
624
0
170
130
613
60

590
598
756
762
589
509
505
633
886
945
519
411
816
843
548
507
889
425
486
602
501
506
817
535
824
0
0
641
851
258
850
742
844
335
485
104
110
0
538
153
779
273
378
481
497
488
479
206
207
203
373
489
877
908
907
902
901
901
908
908
822
822
816
913
305
912
907
905
819
652
857
873
621
476
469
478
464
116
737
136
415
135
136
139
147
138
141
0
0
276
666
525
724
904
904
538
754
904
852
779
845
781
778
665
418
884
712
13
557
446
330
293
673
687
644
653
786
645
706
639
536
477
0
170
369
365
487
521
458
872
872
777
794
687
785
802
778
489
467
481
818
409
427
691
360
607
280
260
569
605
482
615
569
567
567
411
280
700
231
201
154
0
0
0
702
732
849
545
637
639
681
635
737
694
698
520
839
846
807
807
476
847
249
213
230
0
669
847
417
248
847
847
948
727
466
794
743
888
875
444
626
625
754
799
5
893
900
930
897
838
916
643
468
580
576
508
585
512
670
259
324
800
769
783
796
765
761
761
670
758
691
701
795
523
909
850
828
831
600
374
577
855
856
845
745
777
854
747
746
644
628
617
434
429
586
596